query GetUserDetails($userLogin: String!) {
  user(login: $userLogin) {
    login
    name
    avatarUrl
    followers {
      totalCount
    }
    following {
      totalCount
    }
    starredRepositories {
      totalCount
    }
  }
}
